[tool.black]
line-length = 109
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'


[tool.interrogate]
ignore-init-method = true
ignore-init-module = false
ignore-magic = true
ignore-semiprivate = true
ignore-private = true
ignore-module = true
fail-under = 80
exclude = ["^test/*"]
ignore-regex = ["^Base*", "^forward*", "^shared*", "^test*", "^raw"]
verbose = 0
quiet = false
whitelist-regex = []
color = true


[tool.isort]
profile = "black"
line_length = 109

[tool.mypy]
ignore_missing_imports = true
follow_imports = "silent"

[tool.pytest.ini_options]
minversion = "6.0"
markers = [
    "slow",
    "gpu",
]

[tool.pylint.'MESSAGES CONTROL']
disable = ["E1101", "E0611", "C0114", "R0901", "W0221", "R0913", "C0103", "W0201", "C0301", "D107", "D100"]
line-length = 109

[tool.pydocstyle]
ignore = ["D1"]
