seed_everything: 42
trainer:
  logger:
    class_path: WandbLogger
    init_args:
      name: foldseek
      project: step
      log_model: true
      dir: wandb
  enable_checkpointing: true
  callbacks:
    - class_path: StochasticWeightAveraging
      init_args:
        swa_lrs: 0.02
    - class_path: ModelCheckpoint
      init_args:
        monitor: train/loss
        save_top_k: 3
        mode: min
    - class_path: RichProgressBar
    - class_path: RichModelSummary
    - class_path: LearningRateMonitor
  gradient_clip_val: 1.0
  accumulate_grad_batches: 4
  max_epochs: 10000
  log_every_n_steps: 50
  accelerator: gpu
model:
  local_module: GINE
  global_module: Performer
  hidden_dim: 512
  num_layers: 24
  num_heads: 16
  dropout: 0.0
  attn_dropout: 0.0
  alpha: 0.01
  weighted_loss: false
data:
  pre_transforms:
    - class_path: torch_geometric.transforms.Center
    - class_path: torch_geometric.transforms.NormalizeRotation
  transforms:
    - class_path: step.data.PosNoise
      init_args:
        sigma: 1.0
        plddt_dependent: false
    - class_path: torch_geometric.transforms.RadiusGraph
      init_args:
        r: 7.0
    - class_path: torch_geometric.transforms.ToUndirected
    - class_path: torch_geometric.transforms.Spherical
    - class_path: step.data.MaskTypeAnkh
      init_args:
        pick_prob: 0.2
  num_workers: 16
  shuffle: true
  batch_sampling: true
  max_num_nodes: 1024
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0001
    betas:
      - 0.9
      - 0.999
    eps: 1.0e-08
    weight_decay: 0.0
lr_scheduler:
  class_path: cosine_annealing_warmup.CosineAnnealingWarmupRestarts
  init_args:
    first_cycle_steps: 10000
    cycle_mult: 1.0
    max_lr: 0.0001
    min_lr: 0.00001
    warmup_steps: 1000
    gamma: 1.0
