seed_everything: 42
trainer:
  enable_checkpointing: true
  # profiler: pytorch
  callbacks:
    - class_path: ModelCheckpoint
      init_args:
        monitor: train/loss
        mode: min
        dirpath: checkpoints
        save_last: true
        save_on_train_epoch_end: true
    - class_path: RichProgressBar
    - class_path: RichModelSummary
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: step
  max_epochs: 10
  log_every_n_steps: 1000
  accelerator: gpu
  precision: bf16-mixed
  strategy: ddp
  devices: -1
  num_nodes: 4
model:
  class_path: step.models.DenoiseModel
  init_args:
    hidden_dim: 512
    pe_dim: 128
    pos_dim: 128
    num_layers: 12
    attn_type: performer
    dropout: 0.5
    alpha: 1.0
    predict_all: true
data:
  class_path: FoldSeekDataModule
  init_args:
    pre_transforms:
      - class_path: torch_geometric.transforms.Center
      - class_path: torch_geometric.transforms.NormalizeRotation
    transforms:
      - class_path: step.data.PosNoise
        init_args:
          sigma: 1.0
          plddt_dependent: false
      - class_path: step.data.MaskType
        init_args:
          pick_prob: 0.2
      - class_path: torch_geometric.transforms.RadiusGraph
        init_args:
          r: 10.0
      - class_path: torch_geometric.transforms.ToUndirected
      - class_path: step.data.transforms.RandomWalkPE
        init_args:
          walk_length: 20
          attr_name: pe
    num_workers: 10
    shuffle: true
    batch_sampling: false
    batch_size: 16
    # max_num_nodes: 8192
