seed_everything: true
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      name: foldseek
      project: step
      log_model: true
      dir: wandb
      tags: [foldseek]
  enable_checkpointing: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.StochasticWeightAveraging
      init_args:
        swa_lrs: 0.02
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: train/loss
        save_top_k: 3
        mode: min
    - class_path: pytorch_lightning.callbacks.RichProgressBar
    - class_path: pytorch_lightning.callbacks.RichModelSummary
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
  gradient_clip_val: 1.0
  accumulate_grad_batches: 4
  max_epochs: 10000
  log_every_n_steps: 50
  accelerator: gpu
model:
  local_module: GENConv
  global_module: Performer
  hidden_dim: 512
  num_layers: 24
  num_heads: 16
  dropout: 0.0
  attn_dropout: 0.0
  alpha: 1.0
  weighted_loss: false
data:
  root: /scratch/SCRATCH_NVME/ilya/ProtPreTrain/data/foldseek
  pre_transforms:
    - class_path: torch_geometric.transforms.Center
    - class_path: torch_geometric.transforms.NormalizeRotation
    - class_path: torch_geometric.transforms.RadiusGraph
      init_args:
        r: 7.0
    - class_path: torch_geometric.transforms.ToUndirected
  transforms:
    - class_path: step.data.PosNoise
      init_args:
        sigma: 1.0
        plddt_dependent: false
    - class_path: step.data.MaskTypeAnkh
      init_args:
        pick_prob: 0.2
  num_workers: 16
  shuffle: true
  batch_sampling: true
  max_num_nodes: 2048
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0001
    betas:
      - 0.9
      - 0.999
    eps: 1.0e-08
    weight_decay: 0.0
lr_scheduler:
  class_path: cosine_annealing_warmup.CosineAnnealingWarmupRestarts
  init_args:
    first_cycle_steps: 1000
    cycle_mult: 1.0
    max_lr: 0.0001
    min_lr: 0.00001
    warmup_steps: 50
    gamma: 1.0
