seed_everything: true
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      name: test
      save_dir: null
      project: pretrain_alphafold
      log_model: true
      dir: wandb
  enable_checkpointing: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.StochasticWeightAveraging
      init_args:
        swa_lrs: 0.02
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: train/loss
        save_top_k: 1
        mode: min
    - class_path: pytorch_lightning.callbacks.RichProgressBar
    - class_path: pytorch_lightning.callbacks.RichModelSummary
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
  gradient_clip_val: 1.0
  num_nodes: 1
  devices: -1
  auto_select_gpus: true
  overfit_batches: 0
  accumulate_grad_batches: null
  max_epochs: 10000
  log_every_n_steps: 50
  accelerator: gpu
  strategy: null
  sync_batchnorm: false
model:
  local_module: GENConv
  global_module: Performer
  hidden_dim: 1024
  num_layers: 16
  num_heads: 16
  dropout: 0.0
  attn_dropout: 0.0
  alpha: 1.0
  weighted_loss: false
data:
  root: data/swissprot
  archive: null
  pre_transforms:
    - class_path: torch_geometric.transforms.Center
    - class_path: torch_geometric.transforms.NormalizeRotation
    - class_path: torch_geometric.transforms.RadiusGraph
      init_args:
        r: 7.0
    - class_path: torch_geometric.transforms.ToUndirected
  transforms:
    - class_path: protpretrain.data.PosNoise
      init_args:
        sigma: 1.0
        plddt_dependent: false
    - class_path: protpretrain.data.MaskType
      init_args:
        pick_prob: 0.15
  batch_size: -1
  num_workers: 16
  shuffle: true
  batch_sampling: true
  max_num_nodes: 10000
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.0001
    betas:
      - 0.9
      - 0.999
    eps: 1.0e-08
    weight_decay: 0.01
lr_scheduler:
  class_path: protpretrain.utils.LinearWarmupCosineAnnealingLR
  init_args:
    warmup_epochs: 1
    max_epochs: 500
    warmup_start_lr: 1.0e-05
    eta_min: 1.0e-06
